default_agent: emergingtechnologyresearch
agents:
  emergingtechnologyresearch:
    name: emergingtechnologyresearch
    entrypoint: D:/Data science projects/llm_projects/Enterprise_grade_agentic_ai/emergingtechnologyresearch/src/emergingtechnologyresearch/agentcore.py
    deployment_type: container
    runtime_type: null
    platform: linux/amd64
    container_runtime: none
    source_path: D:\Data science projects\llm_projects\Enterprise_grade_agentic_ai\emergingtechnologyresearch\src\emergingtechnologyresearch
    aws:
      execution_role: arn:aws:iam::038777381576:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-a90556d9aa
      execution_role_auto_create: false
      account: 038777381576
      region: us-east-1
      ecr_repository: 038777381576.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-emergingtechnologyresearch
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: emergingtechnologyresearch-YmrcKp6jwq
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:038777381576:runtime/emergingtechnologyresearch-YmrcKp6jwq
      agent_session_id: a560822d-fb87-4d23-a700-54a0a1fa15cb
    codebuild:
      project_name: bedrock-agentcore-emergingtechnologyresearch-builder
      execution_role: arn:aws:iam::038777381576:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-a90556d9aa
      source_bucket: bedrock-agentcore-codebuild-sources-038777381576-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: emergingtechnologyresearch_mem-yXxVpm9hjX
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:038777381576:memory/emergingtechnologyresearch_mem-yXxVpm9hjX
      memory_name: emergingtechnologyresearch_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
